# Generated by Django 5.0.3 on 2024-03-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'list',
            },
        ),
    ]
