# Generated by Django 5.0.3 on 2024-03-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
